import type { Metadata } from "next";
import { Geist, Geist_Mono, Old_Standard_TT } from "next/font/google";
import "./globals.css";
import { Header } from "@/features/Header/Header";
import FooterPage from "@/features/Footer/FooterPage";

const oldStandard = Old_Standard_TT({ weight: ['400','700'], subsets: ['latin'] });


const _geist = Geist({ subsets: ["latin"] });
const _geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased ${_geist.className} ${_geistMono.className} ${oldStandard.className}`}
      >
        <Header />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
